version: '3.9'

services:
  redis:
    image: 'redislabs/redismod'
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
