version: '3.9'

services:
  redis:
    image: 'redis/redis-stack:7.2.0-v0'
    ports:
      - '6379:6379'
      - '8001:8001'
    volumes:
      - ./data:/data
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
