version: '3.9'

services:

  app:
    image: ghcr.io/malyshevhen/redisearch-spring-demo:pr-4
    ports:
      - '8080:8080'
    depends_on:
      - redis
    restart: on-failure

  redis:
    image: 'redis/redis-stack:7.2.0-v0'
    ports:
      - '8001:8001'
    restart: on-failure
